name: Expose Local Web Page

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Authenticate ngrok
        run: ./ngrok authtoken 2BhG4dIUyIvGKAYejnf3NES29Ph_4YyyiswK8LAxMswcjExx1

      - name: Start ngrok
        run: |
          ./ngrok http 8000 > /dev/null &
          sleep 5

      - name: Get ngrok public URL
        id: ngrok
        run: |
          echo "::set-output name=url::$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"

      - name: Display ngrok public URL
        run: |
          echo "Web page URL: ${{ steps.ngrok.outputs.url }}"
















      
