name: Expose Local Web Page

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build web page
        run: |
          mkdir public
          echo "<html><head><title>My Web Page</title><style>body {background-color: lightblue;}</style></head><body><h1>Hello, world!</h1></body></html>" > public/index.html

      - name: Download ngrok
        run: |
          mkdir ngrok
          cd ngrok
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Start ngrok
        run: |
          ./ngrok/ngrok authtoken 2BhG4dIUyIvGKAYejnf3NES29Ph_4YyyiswK8LAxMswcjExx1
          ./ngrok/ngrok http 8080 --log=stdout > ngrok.log &
          sleep 10
          cat ngrok.log | grep "Forwarding" | sed 's/.*http:\/\/localhost:\([0-9]*\).*/\1/' > port.txt
          export PORT=$(cat port.txt)

      - name: Expose ngrok URL
        run: |
          echo "Web page URL: https://$PORT.ngrok.io"












      
