name: Expose Local Web Page

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken YOUR_AUTHTOKEN_HERE
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Create Web Page
      run: echo "<h1>Hello, world!</h1>" > index.html
    - name: Serve Web Page
      run: |
        .\ngrok\ngrok.exe http -host-header="localhost:80" 80





      
