name: Expose Local Web Page

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ngrok
        run: |
          mkdir ngrok
          cd ngrok
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Authenticate ngrok
        run: ./ngrok/ngrok authtoken 2BhG4dIUyIvGKAYejnf3NES29Ph_4YyyiswK8LAxMswcjExx1

      - name: Start local web server
        run: python -m http.server 8000 &

      - name: Wait for server to start
        run: sleep 2

      - name: Expose local web server
        run: ./ngrok/ngrok http 8000













      
