name: Expose Local Web Page

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Create HTML file
      run: |
        echo "<html><body><h1>Hello, world!</h1></body></html>" > index.html
    - name: Start Web Server
      run: python -m http.server 8000



      
