name: Expose Local Web Page

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Install build tools
      run: |
        # Install build tools
        choco install ruby --version=2.7.3 -y
        choco install ruby.devkit -y
        ridk install 1
    - name: Install Jekyll dependencies
      run: |
        # Install Jekyll dependencies
        gem install bundler jekyll
        bundle install
    - name: Build Web Page
      run: |
        # Create a simple web page using Jekyll
        jekyll new my-site
        cd my-site
        echo "Hello, world!" > index.html
    - name: Serve Web Page
      run: |
        # Start the built-in web server to serve the web page
        cd my-site
        jekyll serve --port 4000 &
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe http 4000



      
