name: Expose Local Web Page

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ngrok
        run: |
          sudo apt-get install unzip -y
          curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok.zip

      - name: Authenticate ngrok
        run: ./ngrok authtoken 2BhG4dIUyIvGKAYejnf3NES29Ph_4YyyiswK8LAxMswcjExx1

      - name: Start ngrok and expose web page
        run: |
          nohup ./ngrok http 8000 &
          sleep 5
          curl -s http://localhost:4040/api/tunnels | grep -Eo "https://[^,\"]+" | head -1 > ngrok_url.txt
          cat ngrok_url.txt

      # Rest of the workflow...















      
